return {
	"SmiteshP/nvim-navic",
	event = "LspAttach",
	opts = {
		highlight = true,
		lsp = { auto_attach = true },
		lazy_update_context = false,
		icons = {
			Array = " ",
			Boolean = " ",
			Class = " ",
			Color = " ",
			Constant = " ",
			Constructor = " ",
			Copilot = " ",
			Enum = " ",
			EnumMember = " ",
			Event = " ",
			Field = " ",
			File = " ",
			Folder = " ",
			Function = " ",
			Interface = " ",
			Key = " ",
			Keyword = " ",
			Method = " ",
			Module = " ",
			Namespace = " ",
			Null = " ",
			Number = " ",
			Object = " ",
			Operator = " ",
			Package = " ",
			Property = " ",
			Reference = " ",
			Snippet = " ",
			String = " ",
			Struct = " ",
			Text = " ",
			TypeParameter = " ",
			Unit = " ",
			Value = " ",
			Variable = " ",
		},
	},
	config = function()
		require("nvim-navbuddy").setup({
			window = {
				border = "rounded",
				section = {
					left = { border = "rounded" },
					mid = { border = "rounded" },
					right = { boarder = "rounded" },
				},
			},
		})
	end,
}
